steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'gs://our_mlops_project_bucket/*', 'data/']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/adroit-gravity-410709/training', '-f', 'dockerfiles/train_model.dockerfile', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/adroit-gravity-410709/training']
