steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dark-automata-410710/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dark-automata-410710/testing']
